name: Deploy WordPress 02 to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy WordPress to EC2
        run: |
          cd /var/www/wordpress_02
          git pull origin_02 main
          sudo systemctl restart nginx
