name: Deploy wordpress
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.LINUX_03 }}
          script: |
            cd /var/www/wordpress_02
            git pull origin_02 main
            sudo systemctl restart nginx

